applications:
  mylpg-app:
    type: 'nodejs:20'

    # Dépendances nécessaires à la construction de votre application.
    dependencies:
      nodejs:
        next: "^12.0.0"
        react: "^17.0.2"
        react-dom: "^17.0.2"

    # Exécutez les commandes de construction et de démarrage de votre application.
    hooks:
      # Construisez votre application Next.js avec la commande 'next build'.
      build: |
        set -eux
        npm install

    web:
      commands:
        # Démarrez votre application Next.js en mode production.
        start: npm run dev
      locations:
        '/':
          passthru: true
          # Spécifiez que le trafic doit être transmis à votre application.
         

    # Configuration de l'emplacement de vos fichiers statiques (construits).
    mounts:
      '/public':
        source: local
        source_path: public

    # Configurez les ressources de réseau.


services:
  # Configuration du service de base de données (exemple avec MySQL).

# Configurez les routes de votre application.
routes:
  "https://{default}/":
    type: upstream
    upstream: "mylpg-app:http"

  # Redirigez www vers le domaine racine.
  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"
